### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LeuAlmeida** [gabrielemartins/library#1]
Why don't you implement docker engines and steps using docker compose?
[Take a look.](https://www.digitalocean.com/community/tutorials/containerizing-a-node-js-application-for-development-with-docker-compose-pt)

**Comment by gabrielemartins** [comment]
Hi! 
That's a good suggest. I noticed I could do this yesterday when I was reading an article, because I changed my operational system and discovered that there is an error with those Docker commands that are in my Read.me (I'm still trying to learn Docker).
Thank you for the suggestion, I will look for some article or a template to do this.
